### PR TITLE
Remove superfluous logrotate signal killing h2o

### PR DESCRIPTION
**Pull request by infertux**
This seems unnecessary and is actually stopping the h2o process for me(!)

### CODE REVIEW

**Comment by linyows** [comment]
@infertux Thanks pull request. Apparently, I seem to have mistaken the signal. Correctly `SIGHUP`. Change `USR1` to` SIGHUP` and try.

https://h2o.examp1e.net/configure/command_options.html

**Comment by infertux** [comment]
> Users may send SIGHUP to the master process to reconfigure or upgrade the server.

`SIGHUP` is needed to update the server, not to reopen the log file. I think h2o reopens the log file automatically. I removed it from my `/etc/logrotate.d/h2o` but I need to wait until tomorrow to double check it's working as expected. I will keep you posted...

**Comment by infertux** [comment]
Please don't merge yet. This does not work as expected. h2o keeps writing to `access.log.1` instead of the new file named `access.log`. I will try with `SIGHUP` and let you know tomorrow...

**Comment by infertux** [comment]
@linyows Yes it's working fine with `SIGHUP`. I think it's good to merge.

**Comment by linyows** [comment]
Thanks!

**Pull request merged**
